import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const jost = Jost({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Case Boutique",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={jost.className}>
        <Navbar />

        <main className='flex flex-col min-h-[calc(100vh-3.5rem-1px)]'>
          <div className='flex flex-1 flex-col h-full'>{children}</div>

          <Footer />
        </main>
      </body>
    </html>
  );
}
